service: serverless-sample 

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

package:
 include:
   - ./node_modules/http-status-codes/**

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: test/hello
          method: get

  tslambda:
    handler: tshandler.handler
    events:
      - http:
          path: tshandler/test
          method: get
    
  posthandler:
    handler: posthandler.postHandler
    events:
      - http:
          path: posthandler/post
          method: post

